### ISSUE TITLE
Add Alibaba ECS support

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/productinfo#25]
https://www.alibabacloud.com/help/doc-detail/25378.htm#g5

**Comment by baluchicken** [comment]
* Cluster info related API calls for Alibaba
* All off these can be tried out https://api.aliyun.com/?spm=a2c1g.8271268.10000.2.fadcdf25ibECdK here by selecting the Elastic Compute Service
    * Available regions: https://www.alibabacloud.com/help/doc-detail/25609.htm?spm=a2c63.p38356.a3.124.5952466a1iIJnW#DescribeRegions
    * Available zones: https://www.alibabacloud.com/help/doc-detail/25610.htm?spm=a2c63.p38356.a3.125.5952466a1iIJnW#DescribeZones
    * Instance types: https://www.alibabacloud.com/help/doc-detail/25620.htm?spm=a2c63.p38356.b99.275.47a5466aGhsL7N
    * Spot price: https://www.alibabacloud.com/help/doc-detail/60400.htm?spm=a2c63.p38356.a3.18.5952466apwsb1q#DescribeSpotPriceHistory
    * Price: https://api.aliyun.com/?#product=Ecs&search=Price&api=DescribePrice&params={}&tab=DEMO&lang=JAVA&_=r

**Comment by lpuskas** [comment]
This has been added to the master and also to the service-support brnach
