### ISSUE TITLE
improve logging

### ISSUE THREAD

**Issue by martonsereg** [banzaicloud/productinfo#41]
1.: we should create a consistent way of initialising loggers, similarly to Pipeline:
https://github.com/banzaicloud/pipeline/pull/798

2.: we can consider adding a correlation id to requests for better tracing and error handling:
https://github.com/banzaicloud/pipeline/pull/787/files

3.: configure gin to use logrus:
https://github.com/banzaicloud/pipeline/pull/793/files

4.: add provider's name as a field for every log message that's related to a specific provider

5.: add a scrape id to every scrape message to be able to distinguish between them

6.: alibaba package shouldn't use the `"github.com/aliyun/alibaba-cloud-sdk-go/sdk/log"` package for logging but the standard `logrus` instead that's used everywhere else

**Comment by sagikazarmark** [comment]
I think we can move the necessary packages to a common platform package to use it in more than one projects.

You might also be interested in banzaicloud/pipeline#957

**Comment by prekoa** [comment]
#63 #64
