### ISSUE TITLE
code enhancements (viper, logging, etc)

### ISSUE THREAD

**Issue by martonsereg** [banzaicloud/productinfo#44]
from the review of https://github.com/banzaicloud/productinfo/pull/43:

- [ ] inject configuration values and do not access viper directly: (https://github.com/banzaicloud/productinfo/pull/43/files/97f9eb1e934ec12d8079e8192df5460a240d1319#r214339225)

- [x] init waitgroup a few lines later, to prevent creating it unnecessarily:
https://github.com/banzaicloud/productinfo/pull/43/files/97f9eb1e934ec12d8079e8192df5460a240d1319#r214339649

**Comment by lpuskas** [comment]
this has been already addressed
